num1=int(input("enter the first number "))
num2=int(input("enter the second number "))
addition=num1+num2
subtraction=num1-num2
multiplication=num1*num2
division=num1/num2
print("addition=",addition)
print("subtraction=",subtraction)
print("multiplication=",multiplication)
print("division=",division)